let handler = async(m, { conn, text }) => {
  let who = m.mentionedJid[0]
  if (!who) return m.reply('_Tag Salah Satu!_')
  let repeat = `
*「  REPEAT TAG  」*

@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}
@${who.split("@")[0]}

*「    SGDC-BOT    」*
`.trim()

conn.reply(m.chat, repeat, m, {
           contextInfo: { 
                 mentionedJid: [who]
          } 
      })
  }
  
handler.command = /^(rptag|repeattag)$/i
handler.owner = false
handler.mods = false
handler.premium = true
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null


module.exports = handler

//  MUHAMMAD AFDHAN
